config/routes.rb
Rails.application.routes.draw do
  root to: 'main#home'
  get 'servico/index', to: 'servico#index'
  get 'servico/dados', to: 'servico#dados'
  get 'servico/listas', to: 'servico#listas'
  get 'servico/problemas', to: 'servico#problemas'
  get 'servico/:id', to: 'servico#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/canal.rb
class Canal < ApplicationRecord
    belongs_to :etapa
    has_one :servico, through: :etapa
    has_one :orgao, through: :etapa
end

app/models/documento.rb
class Documento < ApplicationRecord
    belongs_to :etapa
    has_one :service, through: :etapa
    has_one :orgao, through: :servico
end

app/models/etapa.rb
class Etapa < ApplicationRecord
    belongs_to :servico
    has_many :documentos
    has_many :canals
    has_many :taxas
    has_one :orgao, through: :servico
end

app/models/orgao.rb
class Orgao < ApplicationRecord
    has_many :servicos
    has_many :etapas, through: :servicos
    has_many :canals, through: :etapas
    has_many :documentos, through: :etapas
    has_many :taxas, through: :etapas
end

app/models/prob_portal.rb
class ProbPortal < ApplicationRecord
end

app/models/servico.rb
class Servico < ApplicationRecord
    belongs_to :orgao
    has_many :etapas
    has_many :canals, through: :etapas
    has_many :documentos, through: :etapas
    has_many :taxas, through: :etapas
end

app/models/taxa.rb
class Taxa < ApplicationRecord
    belongs_to :etapa
    has_one :servico, through: :etapa
    has_one :orgao, through: :etapa
end

app/models/ultima_atualizacao.rb
class UltimaAtualizacao < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end
end

app/controllers/servico_controller.rb
class ServicoController < ApplicationController
  def index
    common
  end
  
  def show
    common
    @servico = Servico.find(params[:id])
    @etapas = Etapa.all.select {|c| c.servico_id == @servico.id}
    @orgao = Orgao.find(@servico.orgao_id)
    @avaliacoes_total = @servico.avaliacoes_positivas + @servico.avaliacoes_negativas
    @ind_aprov = ((@servico.avaliacoes_positivas.to_f/@avaliacoes_total)*100).round(2)
    @impacto_avaliacoes = (((@servico.avaliacoes_positivas.to_f/@soma_positivas_portal) - (@servico.avaliacoes_negativas.to_f/@soma_negativas_portal))*100).round(2)
    @dias_ultmod = (Date.today - @servico.data_modificacao).to_i
    @etotal = @servico.etapas.length
    @edigital = digitalize(@etapas)
    @ind_dig = ((@edigital.to_f/@etotal)*100).round(2)

    if @servico.nomes_populares.nil? || @servico.nomes_populares.empty?
      @nomes_populares = []
    else
      @nomes_populares = @servico.nomes_populares.to_s.gsub("[\"","").gsub("\"]","").split("\", \"")
    end

    if @servico.segmentos.nil? || @servico.segmentos.empty?
      @segmentos = []
    else
      @segmentos = @servico.segmentos.to_s.gsub("[\"","").gsub("\"]","").split("\", \"")
    end

    if @servico.palavras_chave.nil? || @servico.palavras_chave.empty?
      @palavras_chave = []
    else
      @palavras_chave = @servico.palavras_chave.to_s.gsub("[\"","").gsub("\"]","").split("\", \"")
    end
    selos  
  end

  def dados
    common
    @qtd_servicos = @servicos.length
    @servicos_com_avaliacao = 0 
    @total_gratuitos = 0
    @total_botao_solicitar = 0
    @qtd_etapas = 0
    @qtd_digitais = 0
    @tx_digital = 0
    @serv_total_digital = 0
    @servicos.each do |s|
      @total_gratuitos += s.gratuito == true ? 1 : 0
      @total_botao_solicitar += s.botao_solicitar == true ? 1 : 0
      @servicos_com_avaliacao += ((s.avaliacoes_positivas != nil ? s.avaliacoes_positivas : 0) + (s.avaliacoes_negativas != nil ? s.avaliacoes_negativas : 0)) > 0 ? 1 : 0
      @qtd_etapas += s.etapas.length
      @qtd_digitais += s.qtd_etapas_digitais
      @tx_digital += s.qtd_etapas_digitais.to_f/s.qtd_etapas_total
      @serv_total_digital += s.qtd_etapas_digitais == s.qtd_etapas_total ? 1 : 0
    end
  end
  
  def problemas
    common
    @problemas_portal = ProbPortal.all
    @semcat = @servicos.select {|sc| sc.categoria_nivel1.empty? || sc.categoria_nivel2.empty? || sc.categoria_nivel3.empty?}
  end
  
  def listas
    common
    @docs = []
    @documentos.each do |dd|
      @docs << dd.nome
    end
    @count_docs = @docs.group_by(&:itself).transform_values(&:count).sort_by {|k, v| -v}
    @serv_by_docs = {}
    @sbd = {}
    @teste = []
    @servicos.each do |serv|
      serv.etapas.each do |etp|
          @teste << etp.documentos
      end
      @serv_by_docs[serv.id] = @teste
      @teste = []
    end
    @serv_by_docs.each do |id, docs|
      @sbd[id] = docs.flatten.length
    end
    @list_org = []
    @orgaos.each do |o|
      @list_org << [o.servicos.length, o.nome]
    end
    @list_org = @list_org.sort {|x,y| -(x <=> y)}
  end


  private

  def digitalize(etapas)
      edigital = 0
      digitais = ["web", "e-mail", "aplicativo-movel", "web-consultar", "web-acompanhar", "web-preencher", "web-inscrever-se", "web-emitir", "web-declarar", "web-agendar", "web-calcular-taxas"]
      dd = 0
      etapas.each do |e|
        etapa = Etapa.find_by("api_id": e.api_id).id
        canais = Canal.all.select {|c| c.etapa_id == etapa}
          canais.each do |can|
            if digitais.include?(can.tipo)
              dd += 1
            end
          end
          if dd > 0
            edigital += 1
            dd = 0
          end
      end
      return edigital
  end

  def common
    @bruto = Servico.all
    @servicos = []
    @problemas = []
    @bruto.each do |b|
      if b.nome != nil
        @servicos << b
      else
        @problemas << b
      end
    end
    @orgaos = Orgao.all
    @documentos = Documento.all
    @canais = Canal.all
    @etapas = Etapa.all
    @total_avaliacoes_portal = 0
    @soma_positivas_portal = 0
    @soma_negativas_portal = 0
    @total_dias_atualizacao_portal = 0
    @não_atualizados_ano_ou_mais = 0
    @servicos.each do |s|
      @dias = (Date.today - s.data_modificacao).to_i
      @não_atualizados_ano_ou_mais += @dias > 365 ? 1 : 0
      @total_dias_atualizacao_portal += @dias
      @total_avaliacoes_portal += s.avaliacoes_positivas.to_i + s.avaliacoes_negativas.to_i
      @soma_positivas_portal += s.avaliacoes_positivas != nil ? s.avaliacoes_positivas : 0
      @soma_negativas_portal += s.avaliacoes_negativas != nil ? s.avaliacoes_negativas : 0
    end

    def selos
       # Início Selo Aprovação
      if @ind_aprov >= 80
        @apicone='laugh-beam'
        @class="otimo"
      elsif @ind_aprov > 60 && @ind_aprov < 80
        @apicone='smile-beam'
        @class="bom"
      elsif @ind_aprov >= 50 && @ind_aprov <= 60
        @apicone='meh'
        @class="medio"
      elsif @ind_aprov > 25 && @ind_aprov < 50
        @apicone='frown'
        @class="ruim"
      else
        @apicone='sad-cry'
        @class="pessimo"
      end
    # Fim Selo Aprovação
    # Inicio Selo Impacto
      if @impacto_avaliacoes > 0 
        @seta_impacto = 'arrow-alt-circle-up'
        @stilo = "otimo"
        @seta_impacto = 'minus-circle'
        @stilo = "medio"
      else
        @seta_impacto = 'arrow-alt-circle-down'
        @stilo = "pessimo"
      end
    # Fim Selo Impacto
    # Início Selo Atualização
      if @dias_ultmod <= 90
        @txt = "3 meses ou menos"
        @atualicon='laugh-beam'
        @nota="otimo"
      elsif @dias_ultmod > 90 && @dias_ultmod <= 180
        @txt = "Entre 3 e 6 meses"
        @atualicon='smile-beam'
        @nota="bom"
      elsif @dias_ultmod > 180 && @dias_ultmod <= 365
        @txt = "Entre 6 meses e 1 ano"
        @atualicon='meh'
        @nota="medio"
      elsif @dias_ultmod > 365 && @dias_ultmod <= 730
        @txt = "Entre 1 e 2 anos"
        @atualicon='frown'
        @nota="ruim"
      else
        @txt = "Mais de 2 anos"
        @atualicon='sad-cry'
        @nota="pessimo"
      end
    # Fim Selo Atualização
    # Início Selo Digitalização
      if @ind_dig >= 80
        @digicon='laugh-beam'
        @clss="otimo"
      elsif @ind_dig > 60 && @ind_dig < 80
        @digicon='smile-beam'
        @clss="bom"
      elsif @ind_dig >= 50 && @ind_dig <= 60
        @digicon='meh'
        @clss="medio"
      elsif @ind_dig > 25 && @ind_dig < 50
        @digicon='frown'
        @clss="ruim"
      else
        @digicon='sad-cry'
        @clss="pessimo"
      end
    # Fim Selo Digitalização
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/servico_helper.rb
module ServicoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dados do Portal Gov.br</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
      <li class="nav-item active">
          <a class="navbar-brand" href="/#"><span style="font-size:130%;margin-left:4px"><%=fa_icon('home')%></span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/servico/index">Lista de Serviços</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=servico_dados_path%>">Estatísticas de Serviços</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=servico_listas_path%>">10 mais</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=servico_problemas_path%>">Problemas</a>
        </li>
      </ul>
    </div>
  </nav>
  <body>
  <%@data = []%>
  <%@dat = UltimaAtualizacao.last.data.to_s.split("-")%>
  <%@data = @dat.reverse.join("/")%>
  <p class="ultdata"><i>Última Atualização dos dados: <%=@data%></i></p>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/main/home.html.erb
<br>
<h1>O que você deseja ver?</h1>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <a href="<%=servico_index_path%>">
                <div class="homecard">
                    <h6>Informações dos Serviços</h6>
                    <div class="cardtxt">
                        <p> <span class="icon"><%=image_tag "lista_servicos.png", alt: "lista de servicos", width: "50%" %></span> Nesta sessão você verá a lista de todos os serviços presentes tanto no Portal quanto na API e poderá ver características individuais de cada serviço clicando neles.</p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-4">
            <a href="<%=servico_dados_path%>">
                <div class="homecard">
                    <h6>Estatísticas dos Serviços</h6>
                    <div class="cardtxt">
                        <p> <span class="icon"><%=image_tag "estatisticas.png", alt: "lista de servicos", width: "50%"%></span> Aqui você pode ver os "grandes números" da área de serviços do Portal assim como alguns gráficos relativos à visitação e ao uso dele.</p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-4">
            <a href="<%=servico_listas_path%>">
                <div class="homecard">
                    <h6>Listas 10 mais</h6>
                    <div class="cardtxt">
                        <p> <span class="icon"><%=image_tag "dezmais.png", alt: "lista de servicos", width: "50%"%></span> Nesta parte estão as listas comparativas. "Quais são os documentos mais pedidos?" "Quais órgãos tem mais serviços no Portal?" e assim por diante.</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <br>
     <div class="row">
        <div class="col-sm-4">
            <a href="<%=servico_problemas_path%>">
                <div class="homecard">
                    <h6>Problemas</h6>
                    <div class="cardtxt">
                        <p> <span class="icon"><%=image_tag "problemas.png", alt: "lista de servicos", width: "50%" %></span> Veja aqui os problemas de registro de serviços que podem hoje ser encontrados na API, no Portal e na relação entre eles.</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

app/views/servico/dados.html.erb
<h1>Estatisticas Gerais dos Serviços</h1>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Quantidade de Serviços:</h6>
                <p><%=@qtd_servicos.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1.').reverse%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Serviços 100% digitais:</h6>
                <p><%=@serv_total_digital.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1.').reverse%></p>
                <p class="posit"><%="#{((@serv_total_digital.to_f/@qtd_servicos)*100).round(2).to_s.gsub(".",",")}%"%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Serviços com Botão Solicitar:</h6>
                <p><%=@total_botao_solicitar.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1.').reverse%></p>
                <p class="posit"><%="#{((@total_botao_solicitar.to_f/@qtd_servicos)*100).round(2).to_s.gsub(".",",")}%"%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Média digitalização dos serviços:</h6>
                <p><%="#{((@tx_digital/@qtd_servicos)*100).round(2)}%"%></p>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Média dias desde a última atualização:</h6>
                <p><%=@total_dias_atualizacao_portal/@qtd_servicos%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Serviços não atualizados há um ano ou mais:</h6>
                <p><%=@não_atualizados_ano_ou_mais.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1.').reverse%></p>
                <p class="posit"><%="#{((@não_atualizados_ano_ou_mais.to_f/@qtd_servicos)*100).round(2).to_s.gsub(".",",")}%"%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Total de Avaliações:</h6>
                <p><%=@total_avaliacoes_portal.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1.').reverse%></p>
                <p class="posit">Avaliações positivas: <%=@soma_positivas_portal.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1.').reverse%><p>
                <p class="negat">Avaliações negativas: <%=@soma_negativas_portal.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1.').reverse%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Aprovação geral:</h6>
                <p><%="#{((@soma_positivas_portal.to_f/@total_avaliacoes_portal)*100).round(2).to_s.gsub(".",",")}%"%></p>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Serviços com Avaliações:</h6>
                <p><%=@servicos_com_avaliacao.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1.').reverse%></p>
                <p class="posit"><%="#{((@servicos_com_avaliacao.to_f/@qtd_servicos)*100).round(2).to_s.gsub(".",",")}%"%></p>
            </div>
        </div>
         <div class="col-sm-3">
            <div class="greycard">
                <h6>Órgãos com serviços no Portal:</h6>
                <p><%=@orgaos.length%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Serviços Gratuitos:</h6>
                <p><%=@total_gratuitos.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1.').reverse%></p>
                <p class="posit"><%="#{((@total_gratuitos.to_f/@qtd_servicos)*100).round(2).to_s.gsub(".",",")}%"%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Média Etapas por Serviço:</h6>
                <p><%=(@qtd_etapas.to_f/@qtd_servicos).round(2).to_s.gsub(".",",")%></p>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Média Etapas Digitais por Serviço:</h6>
                <p><%=(@qtd_digitais.to_f/@qtd_servicos).round(2).to_s.gsub(".",",")%></p>
                <p class="posit"><%="#{(((@qtd_digitais.to_f/@qtd_servicos)/(@qtd_etapas.to_f/@qtd_servicos))*100).round(2).to_s.gsub(".",",")}%"%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Média documentos por serviço:</h6>
                <p><%=(@documentos.length.to_f/@qtd_servicos).round(2).to_s.gsub(".",",")%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Média documentos por etapa:</h6>
                <p><%=(@documentos.length.to_f/@etapas.length).round(2).to_s.gsub(".",",")%></p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="greycard">
                <h6>Média canais por etapa:</h6>
                <p><%=(@canais.length.to_f/@etapas.length).round(2).to_s.gsub(".",",")%></p>
            </div>
        </div>
    </div>
</div>
<br>
<iframe width="100%" height="1000" src="https://datastudio.google.com/embed/reporting/cb74585b-2491-4b86-83c0-fe7b58fe0d86/page/p_kea9em7rnc" frameborder="0" style="border:0" allowfullscreen></iframe>

app/views/servico/index.html.erb
<h1>Serviços do Portal</h1>
<br>
<ul style="list-style-type:none;">
    <%@servicos = @servicos.sort_by { |sv| sv.api_id}%>
    <%@servicos.each do |servico|%>
        <li><a href="<%=servico.id%>"><%="#{servico.api_id} - #{servico.nome} prestado por"%><i><%="#{servico.orgao.nome}"%></i></a></li>
        <p></p>
    <%end%>
</ul>

app/views/servico/listas.html.erb
<h1>Listas Comparativas</h1>
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="greycard">
                <h3>Documentos mais pedidos</h3>
                <ol>
                    <%@count_docs.first(10).each do |k,elm|%>
                        <li><%="#{k} - #{elm} requisições"%></li>
                    <%end%>
                </ol>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="greycard">
                <h3>Serviços que pedem mais documentos:</h3>
                <ol>
                    <%@sbd.sort_by {|k, v| -v}.first(10).each do |key,e|%>
                        <li><a href="<%=Servico.find(key).url%>" target="_blank"><%="#{Servico.find(key).nome} - #{e} requisições"%></a></li>
                    <%end%>
                </ol>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-8">
            <div class="greycard">
                <h3>Órgãos com mais serviços:</h3>
                <ol>
                    <%@list_org.first(10).each do |o|%>
                        <li><%="#{o[1]} - #{o[0]} serviços"%></li>
                    <%end%>
                </ol>
            </div>
        </div>
        <div class="col-sm-2">
        </div>
    </div>
</div>

app/views/servico/problemas.html.erb
<h1>Problemas</h1>
<div id="accordion">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="prob_title mb-0">
                <button class="btn prob_title btn-link collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                    Serviços que estão na API mas não estão no Portal: <%=@problemas.length%> <span class="sym">&#9776</span>
                </button>
            </h5>
        </div>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
                <ul class="list_prob">
                    <%@problemas.sort_by { |sv| sv.api_id}.each do |p|%>
                        <li><a href="https://www.servicos.gov.br/api/v1/servicos/<%=p.api_id%>" target="_blank"><%="#{p.api_id} - #{p.nome_api} do órgão #{p.orgao.nome}"%></a>
                    <%end%>
                </ul>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingTwo">
            <h5 class="prob_title mb-0">
                <button class="btn prob_title btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Serviços que estão no Portal mas não na API: <%=@problemas_portal.length%> <span class="sym">&#9776</span>
                </button>
            </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
                <ul class="list_prob">
                    <%@problemas_portal.each do |pp|%>
                        <li><a href="<%=pp.url%>" target="_blank"><%="#{pp.api_id} - #{pp.nome} -  #{pp.orgao}"%></a>
                    <%end%>
                </ul>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingThree">
            <h5 class="prob_title mb-0">
                <button class="btn prob_title btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Serviços sem todas as categorias: <%=@semcat.length%> <span class="sym">&#9776</span>
                </button>
            </h5>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
                <ul class="list_prob">
                    <%@semcat.each do |sc|%>
                        <%vac_cat = (sc.categoria_nivel1.empty? ? 0:1) + (sc.categoria_nivel2.empty? ? 0:1) + (sc.categoria_nivel3.empty? ? 0:1)%>
                        <li><a href="<%=sc.url%>" target="_blank"><%="#{sc.api_id} - #{sc.nome} -  #{sc.orgao.nome} - Possui #{vac_cat} #{vac_cat == 1 ? "nível de categorização." : "níveis de categorização."}"%></a>
                    <%end%>
                </ul>
            </div>
        </div>
    </div>
</div>